- type: playTimeTracker
  id: JobCivilianC17

- type: job
  id: Citizen
  name: Гражданин
  description: Живи и работай
  playTimeTracker: JobCivilianC17
  applyTraits: false
  joinNotifyCrew: false
  overrideConsoleVisibility: true
  startingGear: CitizenGear
  icon: "JobIconUnionCivilian"
  supervisors: job-supervisors-everyone

  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  special:
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune


- type: playTimeTracker
  id: JobWorkerC17

- type: job
  id: Worker
  name: Разнорабочий
  description: Живи и работай
  playTimeTracker: JobWorkerC17
  applyTraits: false
  joinNotifyCrew: false
  overrideConsoleVisibility: true
  startingGear: CMBWorkerNotReadyGear
  icon: "JobIconUnionPerson"
  supervisors: job-supervisors-gsr-and-factory

  access:
    - UnionBase
    - Engineering
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  special:
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
