- type: department
  id: City14
  name: department-City14
  description: department-City14-description
  color: "#9e6715"
  weight: -15
  roles:
  - Citizen
  - Worker
  - UnionFactoryHead
  - UnionWorkersHead
  - UnionMiner
  - UnionResearcher

- type: department
  id: City14CivilProtection
  name: department-City14CivilProtection
  description: department-City14CivilProtection-description
  color: "Blue"
  weight: -16
  roles:
  - CivilProtactionUnit
  - CivilProtactionUnit02
  - CivilProtactionUnitOfficer
