- type: entity
  name: Базированная База НПЦ
  id: MobBaseNpc
  parent:
  - BaseSimpleMob
  - MobCombat
  - StripableInventoryBase
  - MobPolymorphable
  description: Just a body, be calm.
  abstract: true
  components:
  - type: NameIdentifier
    group: GenericNumber
  - type: CombatMode
  - type: Stripping
  - type: Strippable
  - type: UserInterface
    interfaces:
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface
  - type: ComplexInteraction
  - type: StatusEffects
    allowed:
    - Stutter
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
    - Cold
    - Caustic
    - Asphyxiation
    - Radiation
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Pullable
  - type: LightningTarget
    priority: 2
    lightningExplode: false
  - type: ZombieImmune
  - type: Rotatable
  - type: InputMover
  - type: MobMover
#  - type: Body
#    prototype: Animal
  - type: Climbing
  - type: MeleeWeapon
    angle: 0
    animation: WeaponArcFist
    soundHit:
        collection: Punch
    damage:
        types:
          Blunt: 5
  - type: NPCRetaliation
    attackMemoryLength: 10
  - type: NpcFactionMember
    factions:
      - SimpleNeutral
  - type: Inventory
  - type: Hands
  - type: RotationVisuals
    defaultRotation: 90
    horizontalRotation: 90
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 300
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: MobState
    allowedStates:
    - Alive
    - Dead
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Dead
  - type: SlowOnDamage
    speedModifierThresholds:
      50: 0.5
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 400
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
      - !type:ExplodeBehavior
  - type: Damageable
    damageContainer: Biological
  - type: Puller
  - type: Tag
    tags:
      - CannotSuicide
      - DoorBumpOpener
      - FootstepSound
