- type: entity
  id: BaseCity14Jobs
  abstract: true
  components:
  - type: SalvageJobsData
    rankThresholds:
      0:
        title: salvage-job-rank-title-city14
        bountyGroup: CombineJob
    maxRank:
      title: salvage-job-rank-title-city14-MAX
